SET(CMAKE_SYSTEM_NAME Windows)

SET(CMAKE_C_COMPILER    /bin/x86_64-w64-mingw32-gcc)
SET(CMAKE_CXX_COMPILER  /bin/x86_64-w64-mingw32-g++)

SET(CMAKE_FIND_ROOT_PATH /usr/x86_64-w64-mingw32)

SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)

